### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by sanriopurin** [FabioCZ/NotificationRepeater#1]
Hi!  Awesome app you've got here, it's a real good start!

It would be wonderful if you can make the app (in order of importance):
- emit a notification sound (even the default sound will be immensely useful)
- light up (and blink) the notification LED
- 'floats' the notification in real-time (as messages come in)
- display the notification at the lock screen

**Comment by FabioCZ** [comment]
Thanks for the suggestions - they definitely sound useful. I will try to get these implemented over the weekend.

**Comment by FabioCZ** [comment]
@sanriopurin All of those should now be implemented - see release 1.1.1: https://github.com/FabioCZ/NotificationRepeater/releases/tag/1.1.1 :) Also make sure to go to Notification Repater's app settings and enable notifications and all kinds of behavior you want (lock screen/floating etc.)

**Comment by eliakour** [comment]
Is there an android 6.0 app version?

**Comment by FabioCZ** [comment]
Currently Android 7.0 and above is supported. I can see if it'd be possible to support Android 6.0 as well.

**Comment by eliakour** [comment]
Thanks. I'm very happy to hear about it. 

Στάλθηκε από το Ταχυδρομείο Yahoo σε Android 
 
  Στις Δευ, 21 Ιαν, 2019 στις 23:23, ο χρήστηςFabio Göttlicher<notifications@github.com> έγραψε:   
Currently Android 7.0 and above is supported. I can see if it'd be possible to support Android 6.0 as well.

**Comment by FabioCZ** [comment]
@eliakour See the latest 1.2.0 release - The app should now work on Android 6
https://github.com/FabioCZ/NotificationRepeater/releases/tag/1.2.0
